apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iptv

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- networkpolicy.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: iptv-app

images:
- name: ghcr.io/sojohnnysaid/iptv-app
  newName: ghcr.io/sojohnnysaid/iptv-app
  newTag: 7dffe7d
