apiVersion: v1
kind: Namespace
metadata:
  name: iptv
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    tenant: iptv
    environment: production
